uploads = []
outputs = []

[[generated]]
id = "pL8FP_1RxZsyb0DSW5WnW"
uri = "file://artifacts/galan-web-studios/public/velour.png"
type = "image"
title = "Velour fashion brand website mockup"

[[generated]]
id = "_f11MvQYnSxKY13-ihvRT"
uri = "file://artifacts/galan-web-studios/public/apex.png"
type = "image"
title = "Apex Capital website mockup"

[[generated]]
id = "iHpSLI3Oc6--9HlfoQcUi"
uri = "file://artifacts/galan-web-studios/public/noir.png"
type = "image"
title = "Noir Perfumes website mockup"

[[generated]]
id = "jL4znyeHrsqRXmmD-YC5e"
uri = "file://artifacts/galan-web-studios/public/orion.png"
type = "image"
title = "Orion Studios website mockup"

[[generated]]
id = "rtw2sVKmL5bR848UgsUHE"
uri = "file://artifacts/galan-web-studios/public/lumina.png"
type = "image"
title = "Lumina Health website mockup"

[[generated]]
id = "jEAYn2ApdoCIIa8ZX9aib"
uri = "file://artifacts/galan-web-studios/public/vanta.png"
type = "image"
title = "Vanta Labs website mockup"

[[generated]]
id = "KMjcr1QqI2M1p_lMFRziN"
uri = "file://artifacts/galan-web-studios/public/frames/frame-01.png"
type = "image"
title = "Glowing keyboard screen tight shot"

[[generated]]
id = "95ofm05sRgn3w0H9MB6nP"
uri = "file://artifacts/galan-web-studios/public/frames/frame-02.png"
type = "image"
title = "Slight pull back keyboard"

[[generated]]
id = "VIxRDf3JzH0YvC-Sr994b"
uri = "file://artifacts/galan-web-studios/public/frames/frame-03.png"
type = "image"
title = "More pull back keyboard"

[[generated]]
id = "YnK9Wsk1PBEu_qqJkgaOQ"
uri = "file://artifacts/galan-web-studios/public/frames/frame-04.png"
type = "image"
title = "Pulling back desk revealing"

[[generated]]
id = "CkPx7Dg4eoKO8Jl6Ec1OV"
uri = "file://artifacts/galan-web-studios/public/frames/frame-05.png"
type = "image"
title = "Revealing monitors"

[[generated]]
id = "Ol4xEXyGh1GcaXYhLqxDU"
uri = "file://artifacts/galan-web-studios/public/frames/frame-06.png"
type = "image"
title = "Medium wide monitors"

[[generated]]
id = "-kOAHkX2KGLyD3bPrHBNE"
uri = "file://artifacts/galan-web-studios/public/frames/frame-07.png"
type = "image"
title = "Wide desk shot particles"

[[generated]]
id = "VfgUu9xuzrHBAYo41c_Y5"
uri = "file://artifacts/galan-web-studios/public/frames/frame-08.png"
type = "image"
title = "Wide studio particles"

[[generated]]
id = "bBN2uyP3Gr041f4Bge7Y1"
uri = "file://artifacts/galan-web-studios/public/frames/frame-09.png"
type = "image"
title = "Wide studio more particles"

[[generated]]
id = "b4fb0QkYQHcBzYfbM88FU"
uri = "file://artifacts/galan-web-studios/public/frames/frame-10.png"
type = "image"
title = "Studio revealing space"
